// <auto-generated />
using System;
using FutbinSales.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FutbinSales.Migrations
{
    [DbContext(typeof(SalesContext))]
    partial class SalesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("FutbinSales.Core.Players.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("FutbinSales.Core.Players.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("FutbinSales.Core.Players.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlayerId1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("PlayerId1");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("FutbinSales.Core.Players.Player", b =>
                {
                    b.HasOne("FutbinSales.Core.Players.Category", "Category")
                        .WithMany("Players")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FutbinSales.Core.Players.Sale", b =>
                {
                    b.HasOne("FutbinSales.Core.Players.Player", "Player")
                        .WithMany("Sales")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FutbinSales.Core.Players.Player", null)
                        .WithMany("recentSales")
                        .HasForeignKey("PlayerId1");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("FutbinSales.Core.Players.Category", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("FutbinSales.Core.Players.Player", b =>
                {
                    b.Navigation("Sales");

                    b.Navigation("recentSales");
                });
#pragma warning restore 612, 618
        }
    }
}
